VPN-509-Added two articles to the General folder of new kb VPN
AdguardTeam/KnowledgeBaseVPN pull request #1
Opened 2022-03-25 12:03 UTC by anastasiia-fedotova

2022-03-28 13:25 UTC, vbagirov requested changes

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +When you connect to a network, your computer or mobile device is assigned a unique ID number, or IP address. It usually consists of numbers from 0 to 255, separated by dots or colons. Knowing this se
>the geolocation of the device, and therefore the location

странная фраза

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +When you connect to a network, your computer or mobile device is assigned a unique ID number, or IP address. It usually consists of numbers from 0 to 255, separated by dots or colons. Knowing this se
>can register your IP address and record what you have requested on it

on it - наверное лишнее? Либо from it должно быть, не знаю

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +![How a VPN protocol works](https://cdn.adguard.com/public/Adguard/Blog/vpn/protocol/4.svg)
Андрей не отвечал про свг?

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +## VPN usage
Вот про это уже было раньше, может перенести прям туда всю инфу из этого раздела?

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +**Speed**
Недостатки: "Скорость". Наверное должно быть "сниженная скорость" или типа того?

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +Many VPN providers use protocols that do not allow the VPN connection to imitate normal traffic. Therefore, some online services may detect a VPN connection and restrict access for users with VPNs.
Наверное лучше наоборот: некоторые сервисы блокируют доступ, если детектят впн, а многие протоколы при этом не умеют имитировать обычный трафик. Поэтому проблемы

2022-03-28 13:25 UTC, vbagirov commented on docs/general/how-vpn-works.md
> +* [Browser extension](/adguard-vpn-browser-extension) for Chrome, Firefox, and Edge
Здесь и далее ссылки не будут работать, надо `․․` добавлять и `.md` в конце тоже

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +title: 'Why AdGuard VPN is the better option'
Я думаю что название `.md`-файла стоит укоротить до `why-adguard-vpn`, надо будет учесть ещё это везде, где ссылки на него будут. Сам тайтл можно оставить таким какой есть

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +When getting ready to commit to a [long-term VPN subscription](https://adguard-vpn.com/en/license.html), users most frequently evaluate its speed, security, and price. Those are very important points
ссылку лучше на статью кб про сабскрипшн наверное?

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +When getting ready to commit to a [long-term VPN subscription](https://adguard-vpn.com/en/license.html), users most frequently evaluate its speed, security, and price. Those are very important points
>Let’s look at each of them separately to see why AdGuard VPN is one of a kind and how to use it to its fullest extent.

Фраза как будто из блога взята, мне не очень нравится. Давай просто типа "Адгард ВПН обладает рядом преимуществ:"

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +## 2. Exclusions
Здесь не хватает про исключения сервисов

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +From now you can choose DNS servers from [known DNS providers](/adguard-dns/general/dns-providers.md) such as AdGuard, Cisco, Cloudflare, Google, or Quad9, or even configure to use your own DNS serve
так не получится с ссылкой, ДНС кб будет на отдельном домене

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +## 4. Fastest locations
Меняем на Recommended вроде

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +![Locations](https://cdn.adguard.com/public/Adguard/Blog/vpn/release/VPN_for_Mac/main-en.png)
попроси чуваков с кипра например сделать скрин где России не будет среди рекомендуемых локаций

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +## 5. Compatibility with AdGuard ad blocker
AdGuard Ad Blocker с большой

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +## 8. Split tunneling
Переименовали в Apps Exclusions кажется, уточни

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +## 10. Simultaneous connection allowance
allowance какое-то дурацкое слово тут, давай уберем вообще его

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +AdGuard VPN offers five simultaneous connections to its paid users. We place special emphasis on the word ’*simultaneous*’, and here is why. Some VPN providers only allow to log in to their service o
’*simultaneous*’ - кавычки лишние

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +This little ‘feature’ deserves special mention. In fact, many users crave for dark mode, so we couldn’t ignore it and added a theme switch for all AdGuard VPN products. Choose the one you like more —
убрать кавычки вокруг фичур

2022-03-28 13:25 UTC, vbagirov commented on docs/general/why-adguard-vpn-is-the-better-option.md
> +AdGuard VPN is currently available as a desktop app for macOS and Windows, mobile app for iOS and Android, and as a browser extension for Chrome, Firefox, and Edge. [Give it a try](https://adguard-vp
Это просто скопировано из блога? Кажется лишним в кб-статье

2022-03-29 10:26 UTC, anastasiia-fedotova commented on docs/general/how-vpn-works.md
> +* [Browser extension](/adguard-vpn-browser-extension) for Chrome, Firefox, and Edge
как минимум в ссылки на доки из одной папки не требуют *..*
вот такая ссылка работает *why-adguard-vpn.md*

2022-03-29 16:44 UTC, vbagirov requested changes

2022-03-30 12:46 UTC, vbagirov requested changes

2022-03-30 12:46 UTC, vbagirov commented on docs/general/why-adguard-vpn.md
> +## Up to five connected devices at a time
"10." забылось

2022-03-30 13:21 UTC, vbagirov approved these changes

2022-03-30 14:17 UTC, vbagirov approved these changes

2022-03-31 14:28 UTC, merged