Minor typos
AdguardTeam/KnowledgeBaseVPN pull request #126
Opened 2023-08-22 19:42 UTC by gork7777

I've added comments about these strings in the Crowdin, you can check them out too.

2023-08-25 08:29 UTC, el-termikael requested changes

2023-08-25 08:29 UTC, el-termikael commented on i18n/en/docusaurus-plugin-content-docs/current.json
please don't change anything in i18n and .json files

2023-08-25 09:26 UTC, gork7777 commented on i18n/en/docusaurus-plugin-content-docs/current.json
@el-termikael That's why I changed:
![image](https://github.com/AdguardTeam/KnowledgeBaseVPN/assets/35523759/61022358-83da-468d-b795-c538fce3a426)

2023-08-28 10:27 UTC, el-termikael approved these changes

2023-08-28 10:27 UTC, el-termikael commented on i18n/en/docusaurus-plugin-content-docs/current.json
ah, I see. you are right

2023-08-28 10:27 UTC, merged