Add videos to some articles
AdguardTeam/KnowledgeBaseVPN pull request #131
Opened 2023-09-08 15:51 UTC by ss-orlova

Plus fixed wordings and links

2023-09-11 19:53 UTC, slavaleleka commented on docs/adguard-vpn-for-android/installation.md
> +You can learn more about the AdGuard VPN for Android in [this article](/adguard-vpn-for-android/overview).
урл от корня, `.md` не нужен

2023-09-11 19:54 UTC, slavaleleka commented on docs/general/adguard-vpn-protocol.md
.mdx вообще не нужен

2023-09-12 13:04 UTC, el-termikael requested changes

2023-09-12 13:04 UTC, el-termikael commented on docs/adguard-vpn-browser-extension/overview.md
> +> Note that you can only use AdGuard VPN Browser extension when logged in. Sign in with your AdGuard account or via Google, Facebook, or Apple. In the latter case make sure that your account is bound
ой, как это осталось
нужно заменить blockquote на admonition :::note

2023-09-12 13:04 UTC, el-termikael commented on docs/general/how-to-install.md
> +- [AdGuard VPN Browser extension](/adguard-vpn-browser-extension/installation)
Extension

2023-09-12 13:04 UTC, el-termikael commented on docs/general/why-adguard-vpn.md
> +> The QUIC protocol is rather new and may be unstable. We cannot guarantee its complete reliability for every case.
и тут нужен адмонишн
можно :::caution

2023-09-12 13:04 UTC, el-termikael commented on docs/general/why-adguard-vpn.md
> +> Auto-protection is available in AdGuard VPN for iOS and Android.
тут :::note Compatibility

2023-09-12 13:04 UTC, el-termikael commented on docs/general/why-adguard-vpn.md
>  > We don't endorse the use of AdGuard VPN to bypass copyright regulations.
можно и убрать >

2023-09-12 17:52 UTC, ss-orlova commented on docs/adguard-vpn-browser-extension/overview.md
> +> Note that you can only use AdGuard VPN Browser extension when logged in. Sign in with your AdGuard account or via Google, Facebook, or Apple. In the latter case make sure that your account is bound
исправлено

2023-09-12 17:52 UTC, ss-orlova commented on docs/general/how-to-install.md
> +- [AdGuard VPN Browser extension](/adguard-vpn-browser-extension/installation)
исправлено

2023-09-12 17:55 UTC, ss-orlova commented on docs/general/why-adguard-vpn.md
>  > We don't endorse the use of AdGuard VPN to bypass copyright regulations.
все исправлено

2023-09-13 05:50 UTC, el-termikael approved these changes

2023-09-13 08:40 UTC, merged