Add an article about using AdGuard VPN in problematic countries
AdguardTeam/KnowledgeBaseVPN pull request #138
Opened 2023-10-16 13:02 UTC by ss-orlova

Linked to https://github.com/AdguardTeam/KnowledgeBaseVPN/issues/137

2023-10-16 13:03 UTC, ss-orlova commented on docs/general/vpn-issues.md
> +If adguard-vpn.com is not accessible, use the mirror websites: [adguard-vpn.info](https://adguard-vpn.info/welcome.html) or [adguardvpn-help.com](https://adguardvpn-help.com/welcome.html).
@ameshkov вот эти сайты указывать?

2023-10-16 16:12 UTC, ameshkov commented on docs/general/vpn-issues.md
> +If adguard-vpn.com is not accessible, use the mirror websites: [adguard-vpn.info](https://adguard-vpn.info/welcome.html) or [adguardvpn-help.com](https://adguardvpn-help.com/welcome.html).
только один

2023-10-16 16:13 UTC, ameshkov commented on docs/general/vpn-issues.md
> +If adguard-vpn.com is not accessible, use the mirror websites: [adguard-vpn.info](https://adguard-vpn.info/welcome.html) or [adguardvpn-help.com](https://adguardvpn-help.com/welcome.html).
```
If adguard-vpn.com is not accessible, try using a [mirror website](https://adguardvpn-help.com/).
```

2023-10-16 16:14 UTC, ameshkov commented on docs/general/vpn-issues.md
> +
First of all, you should explain how to install apps.

iOS: change store in App Store
Android: download apk from the website (mirror website)
Windows: download from the website
macOS: download from the website

2023-10-19 09:53 UTC, ameshkov approved these changes

2023-10-19 09:55 UTC, el-termikael requested changes

2023-10-19 09:55 UTC, el-termikael commented on docs/general/vpn-issues.md
> +If don't see AdGuard VPN in your App Store, try changing your Apple ID country:
```suggestion
If don't see AdGuard VPN in your App Store, try changing the country or region in your Apple ID account settings:
```

2023-10-19 09:55 UTC, el-termikael commented on docs/general/vpn-issues.md
> +After changing the region, [install AdGuard VPN](https://apps.apple.com/us/app/adguard-vpn-unlimited-fast/id1525373602).
```suggestion
After changing the region, [download AdGuard VPN](https://apps.apple.com/us/app/adguard-vpn-unlimited-fast/id1525373602).
```

2023-10-19 09:55 UTC, el-termikael commented on docs/general/vpn-issues.md
> +- Use AdGuard VPN’s full apps instead of browser extensions for a more robust and stable connection.
```suggestion
- Use AdGuard VPN’s full-fledged apps instead of browser extensions for a more robust and stable connection.
```

2023-10-19 09:55 UTC, el-termikael commented on docs/general/vpn-issues.md
> +- If you encounter problems connecting to a particular location, try connecting to an alternative one. If all locations fail to respond, restart the app to refresh the server list.
```suggestion
- If you encounter problems connecting to a particular location, try connecting to another one. If all locations fail to respond, restart the app to refresh the server list.
```

2023-10-20 09:22 UTC, ss-orlova commented on docs/general/vpn-issues.md
> +After changing the region, [install AdGuard VPN](https://apps.apple.com/us/app/adguard-vpn-unlimited-fast/id1525373602).
из стора же install говорим

2023-10-20 09:23 UTC, ss-orlova commented on docs/general/vpn-issues.md
> +If don't see AdGuard VPN in your App Store, try changing your Apple ID country:
мне кажется account лишнее тут

2023-10-20 10:35 UTC, el-termikael approved these changes

2023-10-20 10:46 UTC, merged