[AGM-1944] update AGVPN for iOS section
AdguardTeam/KnowledgeBaseVPN pull request #161
Opened 2024-03-05 10:42 UTC by vyanovsky

Update screenshots, instructions, setting names, article structure

2024-03-11 14:56 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
> +To do this, just tap [this link](https://agrd.io/ios_vpn) (leads to App Store) and tap the *GET* button.
не круто прикреплять ссылки к слову «ссылка». лучше переформулировать: [перейдите в апп стор] и нажмите гет. или откройте апп стор на устройстве вручную

2024-03-11 14:58 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
> +Or you can use App Store's search to find AdGuard VPN:
апостроф пофиксим?)

2024-03-11 14:58 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
>      ![AdGuard VPN *mobile_border](https://cdn.adguardvpn.com/content/kb/vpn/ios/adguard-vpn-en.png)
не очень круто что тут Open а не Get, но в целом не критично

2024-03-11 14:58 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
> +1. Wait for the download to finish and for *OPEN* button to appear.
было лучше (

2024-03-11 14:59 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
> +That's it! AdGuard VPN for iOS has been successfully installed on your iOS device.
1. давай уберем уточнение, и так понятно что это для иоса
2. давай пофиксим апостроф

2024-03-11 15:00 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/installation.md
> +If you decided to delete AdGuard VPN for iOS, find its icon on the Home Screen and hold it. In the menu that opens, tap *Remove App*.
```suggestion
If you have decided to delete AdGuard VPN for iOS, find and hold its icon on the home screen. In the menu that opens, tap *Remove App*.
```

2024-03-11 15:02 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +A VPN allows you to create a secure connection to another network on the Internet. It connects a user's computer or mobile device to a server and allows one to browse the internet using a "cover" IP
1. Internet с большой буквы
2. не прикрепляем ссылки к словам «ссылка», «эта статья» и подобным

2024-03-11 15:02 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +The next advantage of AdGuard VPN for iOS is our own VPN protocol. It is extremely difficult to detect compared to other VPN protocols, and it is stable even with a poor Internet connection. You can
тот же коммент про ссылку

2024-03-11 15:07 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +The ping shows the server's response time (in milliseconds) which tells you how fast the connection will be if you choose to connect to that location. Choosing the server with a ping of 22 ms means t
```suggestion
The ping shows the server’s response time in milliseconds. This indicates how fast the VPN connection will be when you connect to that location. Selecting a server with a ping of 22 ms means that a data packet sent to this server will be returned in 22 ms.
```

2024-03-11 15:08 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +In AdGuard VPN you can choose from over 50 locations in dozens of countries.
```suggestion
With AdGuard VPN, you can choose from over 50 locations in dozens of countries.
```

2024-03-11 15:09 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +- enter them manually in the app
```suggestion
- Enter them manually in the app
```

2024-03-11 15:10 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +- add them directly from the browser by sharing the desired pages with AdGuard VPN
```suggestion
- Add them directly from the browser by sharing the desired pages with AdGuard VPN
```

2024-03-11 15:10 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +Another useful feature is the import/export of exclusion lists. This way you can import/share exclusion lists from/to other devices.
трудно слеши читаются, лучше переформулировать

2024-03-11 15:11 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +1. Open AdGuard VPN on the device (or in the browser in case of AdGuard VPN browser extension) from where you want to export your lists of exclusions. Find the appropriate section and click the *Expo
in the browser включен в on the device, я бы не уточняла

2024-03-11 15:13 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +**In AdGuard VPN for iOS the export/import feature can be accessed by tapping three-dot icon in upper right corner of the Exclusions screen**.
Валера хейтер артиклей...

```suggestion
**In AdGuard VPN for iOS, the export and import features can be accessed by tapping the three-dot icon in the upper right corner of the Exclusions screen**.
```

2024-03-11 15:14 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +1. Tap Settings icon (⚙) in the bottom right corner of the AdGuard VPN app's main screen.
```suggestion
1. Tap the Settings icon (⚙) in the bottom right corner of the app’s main screen.
```

2024-03-11 15:16 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
>  Here, you can configure AdGuard VPN for iOS as you need using different options: Operating Mode, DNS server, Wi-Fi auto-protection, Color Theme and Advanced Settings.
1. auto-protection надо убрать
2. operating mode глубже
3. Sentence case у названий настроек

 в задаче было же ((

2024-03-11 15:16 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +DNS servers translate a domain name or hostname (e.g., example.com or www.example.com) into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers a choice between several D
ты уверен что это здесь нужно?

2024-03-11 15:18 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +You can choose system default, dark or light theme of the app (available in iOS 13 and later versions).
```suggestion
You can set your app theme to System, Dark, or Light (available on iOS 13 or later).
```

2024-03-11 15:19 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +In *Advanced settings* you can find 4 sections — Operating mode, Logging level, Export logs and system info, Diagnostic info.
```suggestion
In *Advanced settings*, you can find 4 sections — *Operating mode*, *Logging level*, *Export logs and system info*, and *Diagnostic info*.
```

2024-03-11 15:22 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +In **VPN** mode, the [AdGuard VPN protocol](/general/adguard-vpn-protocol) is employed, which provides the best combination of speed and security. In this mode, AdGuard VPN will not be able to work a
а зачем ссылка на кб блокировщика? может тогда уж на продуктовую страницу?

```suggestion
The *VPN* mode uses the [AdGuard VPN protocol](/general/adguard-vpn-protocol), which provides the best combination of speed and security. In this mode, AdGuard VPN will not work with [AdGuard Ad Blocker for iOS](https://adguard.com/adguard-ios/overview.html).
```

2024-03-11 15:25 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
>  In **Integrated** mode, AdGuard VPN will be able to work at the same time with AdGuard Ad Blocker for iOS by using the IPSec protocol instead. This protocol is also secure, but a little slower and ea
```suggestion
In **Integrated mode**, AdGuard VPN will be able to work simultaneously with AdGuard Ad Blocker for iOS using the IPSec protocol. This protocol is also secure, but a bit slower and easier to detect. You don’t have to do anything to set up the integration: just install both apps and switch to this mode.
```

2024-03-11 15:27 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +This setting is needed mainly for debug and troubleshooting purposes, due to the fact that Extended and Extreme logging levels record more detailed information which can help identify and fix various
```suggestion
This setting is primarily used for debugging and troubleshooting purposes. The Extended and Extreme logging levels record more detailed information that can help identify and fix various problems or bugs.
```

2024-03-11 17:12 UTC, ss-orlova requested changes

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +5. Press *Send* button.
```suggestion
5. Tap *Send*.
```

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +>If for some reason it is more convenient for you to send us logs in another way, you can export them yourself.
оформление некорректное

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +4. Repeat the actions that led to the error, and note the time when it occurred (e.g. 14:23).
```suggestion
4. Repeat the actions that led to the error and note the time when it occurred (e.g. 14:23).
```

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +6. Go back to *Settings* screen, tap *Support* and then *Report a bug*.
```suggestion
6. Go back to *Settings*, tap *Support* and then *Report a bug*.
```

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +8. Make sure that *Send app logs and system info* checkbox is ticked and press *Send* button.
```suggestion
8. Make sure that *Send app logs and system info* is checked and tap *Send*.
```

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +>If for some reason it is more convenient for you to send us logs in another way, you can export them yourself.
надо вот эти приколы с :::info

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +>If for some reason it is more convenient for you to send us logs in another way, you can export them yourself.
или note...

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/hide-my-email.md
> +Apple's *Hide My Email* feature is a great tool to keep your real email address private when signing up for websites and apps that use Apple ID. You can even use it for private correspondence and man
апостроф

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/hide-my-email.md
> +Apple's *Hide My Email* feature is a great tool to keep your real email address private when signing up for websites and apps that use Apple ID. You can even use it for private correspondence and man
а вообще надо нафиг всю статью переделать, я когда-то создавала задачку

2024-03-11 17:12 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/hide-my-email.md
> +The *Hide My Email* feature is also available in Apple's Mail app. To send an email without disclosing your real email address, simply select *Hide My Email* in the *From* field when composing your m
апостроф

2024-03-14 10:07 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/installation.md
>      ![AdGuard VPN *mobile_border](https://cdn.adguardvpn.com/content/kb/vpn/ios/adguard-vpn-en.png)
не оч понял ты о чем

2024-03-14 10:27 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/installation.md
>      ![AdGuard VPN *mobile_border](https://cdn.adguardvpn.com/content/kb/vpn/ios/adguard-vpn-en.png)
а типа на скрине

2024-03-14 12:43 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/overview.md
> +DNS servers translate a domain name or hostname (e.g., example.com or www.example.com) into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers a choice between several D
вполне, за исключением разве что первого предложения. а так довольно полезно объяснить доп функционал  который не является ВПНом

2024-03-14 17:44 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/installation.md
>      ![AdGuard VPN *mobile_border](https://cdn.adguardvpn.com/content/kb/vpn/ios/adguard-vpn-en.png)
ну переставил скрин ниже, теперь совсем норм

2024-03-14 17:45 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +>If for some reason it is more convenient for you to send us logs in another way, you can export them yourself.
не понял, какой тот же

2024-03-14 17:49 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/solving-problems/integrated-mode.md
> +In *Integrated* mode, in turn, the IPsec protocol is used, which makes it possible for the AdGuard apps to work together.
мне кажется стоит в Юае как раз сделать консистентно, не? оба без мод либо оба с мод
а то сейчас Юае ВПН без мод, а интегрейтед с мод

2024-03-14 18:10 UTC, vyanovsky commented on docs/adguard-vpn-for-ios/solving-problems/logs.md
> +>If for some reason it is more convenient for you to send us logs in another way, you can export them yourself.
а, все, понял

2024-03-19 15:49 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/overview.md
> +If for some reason your VPN connection suddenly drops, *Kill Switch* will automatically terminate the internet connection, making sure your data doesn't leak and your identity stays hidden.
еще чуть-чуть!
```suggestion
If for some reason your VPN connection suddenly drops, *Kill Switch* will automatically terminate the Internet connection, making sure your data doesn’t leak and your identity stays hidden.
```

2024-03-19 15:51 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/integrated-mode.md
> +In *Integrated* mode, in turn, the IPsec protocol is used, which makes it possible for the AdGuard apps to work together.
ну да, но это когда будет...

2024-03-19 15:52 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/integrated-mode.md
> +In *Integrated mode*, *Exclusions* and *DNS server* features are not available.
давай вернем?

2024-03-21 12:32 UTC, ss-orlova commented on docs/adguard-vpn-for-ios/solving-problems/integrated-mode.md
> +In *Integrated mode*, *Exclusions* and *DNS server* features are not available.
```suggestion
In *Integrated mode*, *Exclusions* and *DNS server* are not available.
```

2024-03-21 13:28 UTC, ss-orlova approved these changes

2024-03-21 13:36 UTC, merged