[AGM-1973] Create an article for obtaining trace logs.md
AdguardTeam/KnowledgeBaseVPN pull request #166
Opened 2024-03-12 07:40 UTC by DashaBu

2024-03-12 09:21 UTC, el-termikael requested changes

2024-03-12 09:21 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
>  >If for some reason it is more convenient for you to send us logs in another way, you can export them yourself. To do this, go to **Support** → **Export logs and system info**.
и не хватает пустой строки перед ![Export *border](https://cdn.adtidy.org/content/kb/vpn/windows/logs/export.jpeg)

2024-03-14 09:04 UTC, el-termikael approved these changes

2024-03-20 11:43 UTC, adbuker requested changes

2024-03-20 11:43 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Right click the AdGuard VPN icon in the trace menu and choose *Exit AdGuard VPN*.
trace menu -> tray menu

2024-03-20 11:43 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +In the opened window, agree to close the service
Это окно появится только если пользователь приконнекчен. Лучше написать "если появится диалог (в частности он появится, если установлено соединение с ендпоинтом), то нажмите "ок"

2024-03-20 11:43 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +**Please note**: if you encounter some problems while trying to export logs, there is an alternative way. Please follow these steps:
сейчас выглядит так, как будто этим способом можно воспользоваться только для трейсовых логов - это конечно не так и было бы лучше указать на эту возможность также после [аналогичного блока](https://github.com/AdguardTeam/KnowledgeBaseVPN/pull/166/files#diff-fea39d891fe7293bee9ba427229b74d675567785d0c6dd7b8ab9efe7b75d3d58R50) в общем разделе

2024-03-20 11:43 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Open *My PC* and go to *ProgramData* -> *AdguardVPN* folder in Local Disc (C:)
всё же как и мы общались в переписке - сложно будет объяснить, что такое *ProgramData* -> *AdguardVPN* folder in Local Disc (C:), лучше по шагам
1. open `explorer` app
2. paste `%rpgramdata%/adguardvpn` in the search box
3. ...

2024-03-21 09:58 UTC, el-termikael requested changes

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +**Please note**: if you encounter some problems while trying to export logs, there is an alternative way. Please follow these steps:
Note: if you encounter any problems while trying to export logs, there is an alternative way. Please follow these steps:

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +**Please note**: if you encounter some problems while trying to export logs, there is an alternative way. Please follow these steps:
можно и без ноут, мы обычно адмонишн вместо него ставим, но тут ниже инструкция, не очень подойдёт

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Open `explorer` app
Open the Explorer app

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Locate the folder called **Logs**
Find?

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +**Please note**: if you encounter some problems while trying to export logs, there is an alternative way. Please follow these steps:
тот же коммент, что и выше

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Open `explorer` app
и тут

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Locate the folder called **Logs**
и тут

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Right click the AdGuard VPN icon in the tray menu and choose **Exit AdGuard VPN**.
Right-click

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +Sometimes our support team might ask you to send the trace logs. To do this, you need to do the following steps:
```suggestion
Sometimes our support team might ask you to send them trace logs. To do this, you need to do follow these steps:
```

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +Agree to close the service if you see the warning message.
```suggestion
If you see the warning message, agree to stop the service.
```
скорее так

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Export the recorded logs: **Support** -> **Export logs and system info**.
→

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +**Please note**: if you encounter some problems while trying to export logs, there is an alternative way. Please follow these steps:
и тут тот же коммент

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Open `explorer` app
и тут

2024-03-21 09:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Locate the folder called **Logs**
и тут

2024-03-25 08:55 UTC, el-termikael approved these changes

2024-03-25 11:59 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Paste `%rpgramdata%/adguardvpn` in the search box
%programdata%

2024-03-25 12:03 UTC, adbuker requested changes

2024-03-25 12:03 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
>  ## Collecting and sending standard logs
у нас есть 3 главы `Collecting and sending %logsType% logs`, где последняя часть повторяется, т.е. прям копипаста явная. Может как-то выделить это в отдельную главу, а эти три сделать не `Collecting and sending ...`, а просто `Collecting...`

2024-03-25 12:05 UTC, DashaBu commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Find the folder called **Logs**
не знаю точно почему, но знаю, что так надо)

2024-03-25 12:06 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +title: How to collect and send logs
а кстати на русском это будет потом отдельно?

2024-03-25 12:11 UTC, DashaBu commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
>  ## Collecting and sending standard logs
а мне кажется, что удобно так. Например юзеру сказали, что надо отправить какие-то логи, он идёт в один раздел и сразу всё смотрит, не надо скакать по разным разделам, не?

2024-03-25 12:11 UTC, DashaBu commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +title: How to collect and send logs
перевод статьи? Да, эта задача только на англ была пока

2024-03-25 12:15 UTC, adbuker approved these changes

2024-03-25 12:15 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +title: How to collect and send logs
на русском надо ставить отдельную или вы сами?

2024-03-25 12:15 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
>  ## Collecting and sending standard logs
ну я больше по програмистски - копипаста это зло. Если вы считаете, то так удобнее, то ок. Обсудите плз тогда внутри себя как лучше

2024-03-25 12:15 UTC, adbuker commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Find the folder called **Logs**
ок

2024-03-25 12:17 UTC, DashaBu commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +title: How to collect and send logs
создам задачу

2024-03-25 12:25 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Find the folder called **Logs**
список всё равно будет отрисвываться как 1, 2, 3, но если мы решим добавить/убрать пункты, это повлечёт за собой меньше правок. что-то такое @slavaleleka как-то рассказывал

2024-03-25 12:25 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +title: How to collect and send logs
зачем создавать задачу? у нас же переводы баз знаний в краудине

2024-03-25 12:49 UTC, slavaleleka requested changes

2024-03-25 12:49 UTC, slavaleleka commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +![Report a bug *border](https://cdn.adtidy.org/content/kb/vpn/windows/logs/support_report.jpeg)
надо локально собирать чтобы проверить как оно выглядит
https://uploads.adguard.org/sllxt88ofse0a.png

конкретно тут нужен отступ в 1 таб

2024-03-25 12:57 UTC, slavaleleka commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +![Report a bug *border](https://cdn.adtidy.org/content/kb/vpn/windows/logs/support_report.jpeg)
и ниже тоже

2024-03-26 08:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. Click **Support** (in the menu above) → **Report a bug**.
скобки лишние

2024-03-26 08:58 UTC, el-termikael commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +1. In the opened form enter your email address for feedback and describe the error found, including the time when this error occurred. If you can't reproduce the problem, specify as accurately as pos
```suggestion
1. In the form that opens, enter your email address and describe the error you found, including the time it occurred. If you can't reproduce the problem, be as specific as possible about when it last occurred.
```

2024-03-26 10:22 UTC, slavaleleka approved these changes

2024-03-26 10:50 UTC, el-termikael approved these changes

2024-03-26 10:51 UTC, merged