Fixed commands in Knowledge base for Linux
AdguardTeam/KnowledgeBaseVPN pull request #182
Opened 2024-05-24 10:07 UTC by DashaBu

2024-05-24 10:10 UTC, ss-orlova approved these changes

2024-05-24 12:29 UTC, Aydinv13 requested changes

2024-05-24 12:32 UTC, DashaBu commented on docs/adguard-vpn-for-linux/settings.md
>  Replace `<channel>` with `stable`, `beta`, or `nightly`, depending on your preferences.
только здесь был 'stable'

2024-05-27 07:28 UTC, Aydinv13 approved these changes

2024-05-27 07:29 UTC, merged