Add info about browsers in selective mode
AdguardTeam/KnowledgeBaseVPN pull request #198
Opened 2024-08-09 14:18 UTC by puglieri

2024-08-12 09:54 UTC, el-termikael requested changes

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-ios/overview.md
> +Starting with the version 2.4, when switching to Selective mode, all browsers on the system are automatically added to the exceptions list for more convenience. This change applies under the followin
we don't have the "exceptions list". it's called Exclusions list: https://crowdin.com/editor/adguard-applications/all/en-ru?view=comfortable&filter=basic&value=0#q=exclusions%20list

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-ios/overview.md
> +- The user did not modify selector mode settings prior to v2.4
we neither have "selector mode"...

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> +Starting with the version 2.4, when switching to Selective mode, all browsers on the system are automatically added to the exceptions list for more convenience. This change applies under the followin
AdGuard VPN for iOS is the only VPN product where there still are Regular and Selective mode. In other products, both apps and extensions, it's called differently. Please check that before writing

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> +- The user did not modify selector mode settings prior to v2.4
Why selector...

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-windows/overview.md
> +Starting with the version 2.4, when switching to Selective mode, all browsers on the system are automatically added to the exceptions list for more convenience. This change applies under the followin
same here

2024-08-12 09:54 UTC, el-termikael commented on docs/adguard-vpn-for-windows/overview.md
> +- The user did not modify selector mode settings prior to v2.4
and here

2024-08-12 12:55 UTC, el-termikael requested changes

2024-08-12 12:55 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> -:::info Browsers in Selective mode
you shouldn't remove these blocks — the task was to mention this change for all apps. desktop ones are no less important

2024-08-12 14:55 UTC, puglieri commented on docs/adguard-vpn-for-mac/overview.md
> -:::info Browsers in Selective mode
Wait, I'm a bit confused. 

The task is to mention that switching to Selective mode will add all browsers to exclusions. You've mentioned in another comment that the VPN for iOS is the only product in which there are still a Regular and a Selective mode, is it right? That's why I've removed the other blocks.

2024-08-12 15:51 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> -:::info Browsers in Selective mode
it's called differently, here is a screenshot:
<img width="912" alt="Снимок экрана 2024-08-12 в 18 51 21" src="https://github.com/user-attachments/assets/db3c4f96-3e09-4281-b5aa-f6dffe71205e">
you should always check how features are named in the apps

2024-08-12 15:53 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> -:::info Browsers in Selective mode
<img width="912" alt="Снимок экрана 2024-08-12 в 18 52 28" src="https://github.com/user-attachments/assets/94a5da08-0364-4f11-a143-2315c39f0592">
now you can switch between these two modes (works the same for app exclusions)

2024-08-12 16:29 UTC, Aydinv13 approved these changes

2024-08-13 14:35 UTC, el-termikael requested changes

2024-08-13 14:35 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> +Starting with the version 2.4, all browsers on the system are automatically added to the exclusions list when the VPN is active only for selected apps and websites. This change brings more convenienc
Starting with the version 2.4, all browsers are automatically added to the list of exclusions when the VPN is active only for selected apps and websites. This change brings more convenience for users who were often confused and didn’t know whether or not to consider their browsers as apps or not. It applies under the following conditions:

2024-08-13 14:35 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> +- The user installed the VPN for the first time
The user has installed AdGuard VPN for the first time

2024-08-13 14:35 UTC, el-termikael commented on docs/adguard-vpn-for-mac/overview.md
> +:::info Browsers in the exclusions list
:::info Browsers added to Exclusions

2024-08-17 19:50 UTC, el-termikael commented
closes #188

2024-08-19 10:59 UTC, el-termikael approved these changes

2024-08-19 10:59 UTC, merged

2024-08-19 11:10 UTC, el-termikael commented
don't deploy KB before v2.4 is released