VPN-511 Create AGVPN for Windows Overview
AdguardTeam/KnowledgeBaseVPN pull request #3
Opened 2022-03-28 07:41 UTC by an-martynova

2022-03-30 13:20 UTC, vbagirov requested changes

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +* Protects from network traffic interception (spoofing). AdGuard VPN creates an encrypted tunnel between your device and a remote server. All your Internet traffic passes through this tunnel, so your
Здесь и везде ссылки на другие статьи из впн кб надо сделать относительными. Если не знаешь как, спроси у меня

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +That being said, we recommend to use the option **From the list**, since in each of the eight thematic groups we have placed the most popular services, including all domain names and subdomains relat
Как-то странно, если это рекомендуемый режим, почему он одной строкой в самом конце? Как-то надо получше акцентировать его

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +## Other settings
этот хедер можно убрать, мне кажется. У нас же вроде нет вкладки Other Settings

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +## Unlimited version
Эту часть можно убрать целиком

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +sidebar position: 4
позиция 1

2022-03-30 13:20 UTC, vbagirov commented on docs/adguard-vpn-for-windows/solving-problems/logs.md
> +If you encounter a problem when using AdGuard VPN for Windows, you can inform us about it by sending application logs.
ну не совсем так. ПРоинформировать можно и без логов, но логи значительно помогают в решении проблемы

2022-03-30 18:22 UTC, an-martynova commented on docs/adguard-vpn-for-windows/overview.md
> +## Unlimited version
прямо вместе с заголовком про Анлимитед вершин убирать?

2022-03-31 05:43 UTC, an-martynova commented on docs/adguard-vpn-for-windows/overview.md
> +A VPN, that stands for "virtual private network", is a service that makes your internet connection safe and helps you stay anonymous online. How does it work? Every time you visit a website without u
убрала вообще эту конструкцию, теперь там будет standing for

2022-03-31 13:54 UTC, vbagirov requested changes

2022-03-31 13:54 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +You can set up a DNS server by any provider. We recommend adding [AdGuard DNS](/general/dns-providers#adguard-dns), a server that can protect against advertising, tracking and phishing in addition to
эта ссылка не будет работать, она ведёт на другую кб - днсную. Это другой домен

2022-03-31 13:54 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +## Unlimited version
Прям весь раздел вместе с заголовком убрать

2022-03-31 13:54 UTC, vbagirov commented on docs/adguard-vpn-for-windows/overview.md
> +AdGuard VPN for Windows can work in two modes: **General** or **Selective**. What does this mean? If you want the application to work on all but a few sites, activate the **General mode** and list th
уточни что у двух режимов независимые списки исключений

2022-03-31 14:02 UTC, an-martynova commented on docs/adguard-vpn-for-windows/overview.md
> +You can set up a DNS server by any provider. We recommend adding [AdGuard DNS](/general/dns-providers#adguard-dns), a server that can protect against advertising, tracking and phishing in addition to
Таки что с ней в итоге делать?

2022-03-31 16:10 UTC, vbagirov approved these changes

2022-03-31 16:11 UTC, merged