VPN-780 - add sticky bar
AdguardTeam/KnowledgeBaseVPN pull request #37
Opened 2022-08-31 14:50 UTC by Ars28Fox

2022-09-02 11:59 UTC, 105th requested changes

2022-09-02 11:59 UTC, 105th commented on src/css/custom.css
> +  --vpn-transition-3s: 0.3s ease;
--vpn-transition-300ms тогда уж

2022-09-02 11:59 UTC, 105th commented on src/theme/DocPage/Layout/Main/styles.module.css
> +@media (min-width: 997px) {
ширину хорошо бы в константы

2022-09-02 11:59 UTC, 105th commented on src/theme/DocPage/Layout/Main/index.js
> +import {useDocsSidebar} from '@docusaurus/theme-common';
пробельчики

2022-09-02 11:59 UTC, 105th commented on src/theme/DocPage/Layout/Main/index.js
> +export default function DocPageLayoutMain({hiddenSidebarContainer, children}) {
пробельчики

2022-09-02 11:59 UTC, 105th commented on src/theme/StickyBar/StickyBar.js
> +    switch (getOSName()) {
помень коментом, что использование `<Translate>` нужно для того, чтобы автоматические переводы создались корректно

2022-09-02 11:59 UTC, 105th commented on src/theme/StickyBar/StickyBar.js
> +                                href={`${VPN_WEBSITE_URL}/download.html?auto=1&lbl=knowledge_base`}
не надо ли эту ссылку в тдс завернуть?

2022-09-02 11:59 UTC, 105th commented on static/js/consts.js
> +export const VPN_WEBSITE_URL = 'https://adguard-vpn.com';
вот тут кажется нужен tds

2022-09-02 11:59 UTC, 105th commented on src/theme/StickyBar/StickyBar.js
> +                                                        description="The label for the link to license agreement"
вот тут какая-то ветвистость дикая выходит
имхо, такие вещи лучше выносить в отдельные блоки, которые объявлять выше
и тут просто вставлять типо `{eula}`
но это чисто субъективно

2022-09-02 11:59 UTC, 105th commented on src/theme/StickyBar/StickyBar.module.css
> +@media (min-width: 768px) {
в константы

2022-09-02 11:59 UTC, 105th commented on src/theme/StickyBar/StickyBar.module.css
> +@media (min-width: 768px) {
в константы

2022-09-02 11:59 UTC, 105th commented on static/js/helpers.js
> +import { OS_NAMES, BROWSER_NAMES, VPN_BROWSER_NAMES } from './consts'; // eslint-disable-line import/no-unresolved
`import/no-unresolved` - это зачем?

2022-09-02 11:59 UTC, 105th commented on src/css/custom.css
> +    width: 3rem;
а почему тут `rem` а ниже (src/theme/StickyBar/StickyBar.js) всё через `px`?

2022-09-06 16:35 UTC, Ars28Fox commented on src/theme/StickyBar/StickyBar.module.css
> +@media (min-width: 768px) {
Add SCSS plugin and media vars

2022-09-07 10:49 UTC, 105th approved these changes

2022-09-07 11:43 UTC, merged