VPN-513
AdguardTeam/KnowledgeBaseVPN pull request #5
Opened 2022-03-28 17:34 UTC by NataKiss

AdGuard VPN for Mac new

2022-03-29 11:20 UTC, vbagirov approved these changes

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +<a id="requirements"></a>
хтмл убираем весь

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +## Installation
Давай тут назовём "How to install AdGuard VPN for Mac?", соотв. про удаление "How to uninstall AdGuard VPN for Mac?" и т.д.

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +1. Follow the steps described in the section ["Standard uninstallation"](#uninstall).
Здесь у тебя ссылка на якорь, проверь, как в докузавре маркдауном якоря ставить, и поставь правильный напротив нужной строки

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +3. Click the icon of the found program and enter `com.adguard.mac.vpn` in the search. If there is such a record in the search results, delete it.
such a record in the search results, delete it - удалить запись в поиковой выдаче? или удалить программу?

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +You can learn more about AdGuard VPN for Mac in [this article](https://kb.adguard.com/en/vpn/adguard-vpn-mac/overview).
ссылку поправь, чтоб вела на овервью правильно

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/installation.md
> +2. Open "Finder" and enter `Keychain` in the search.
точно Finder? это ж вроде проводник просто?

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +* [Home screen](#home)
оглавление убираем в докузавре

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +<a id="home"></a>
хтмл убираем

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +The first tab is the *Home* screen. Here you can see AdGuard VPN current status and [operating mode](#exclusions), chosen location (if enabled) and its ping. Ping is the response time of a VPN server
якоря сделай чтоб работали через маркдаун

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +## Exclusions
Вероятно, надо дописать часть про exclusions 2.0, которая только что появилась. Опирайся на инфу из блога

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +The third tab is the *Support* screen. Find answers to any questions in the [FAQ](https://adguard-vpn.com/en/welcome.html#faq) or in the [Knowledge base](https://kb.adguard.com/en/vpn) sections, repo
ссылку на базу знаний (https://kb.adguard.com/en/vpn) надо поправить, она будет не такая

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +Finally, we come to the most important tab — Settings. In the *About program* section you can see the current version of AdGuard VPN, check for updates, visit our official website, and get acquainted
я не уверен что сеттингс - самая важная вкладка. Напиши как-нибудь иначе

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/overview.md
> +## Benefits of the unlimited version
Давай уберем вообще этот раздел, если есть отдельная статья про это

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/solving-problems/logs.md
> +* [Collecting and sending standard logs](#default)
оглавление убираем

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/solving-problems/logs.md
> +<a name="default"></a>
хтмл убираем

2022-03-29 11:20 UTC, vbagirov commented on docs/adguard-vpn-for-mac/solving-problems/logs.md
> +This section is updated regularly. If you have not found a solution to your problem in the articles given in this section, contact [AdGuard technical support](http://kb.adguard.com/en/technical-suppo
эта ссылка не будет работать, напиши пока здесь явным образом мыло саппорта: support@adguard-vpn.com

2022-03-29 11:21 UTC, vbagirov requested changes
Необходимы правки

2022-03-30 09:06 UTC, NataKiss commented on docs/adguard-vpn-for-mac/installation.md
> +You can learn more about AdGuard VPN for Mac in [this article](https://kb.adguard.com/en/vpn/adguard-vpn-mac/overview).
а какая ссылка правильная? adguard.com/knowledgebasevpn/adguard-vpn-for-mac/overview?

2022-03-30 09:26 UTC, NataKiss commented on docs/adguard-vpn-for-mac/installation.md
> +You can learn more about AdGuard VPN for Mac in [this article](https://kb.adguard.com/en/vpn/adguard-vpn-mac/overview).
(/adguard-vpn-for-mac/overview.md)

2022-03-30 09:37 UTC, NataKiss commented on docs/adguard-vpn-for-mac/overview.md
> +The third tab is the *Support* screen. Find answers to any questions in the [FAQ](https://adguard-vpn.com/en/welcome.html#faq) or in the [Knowledge base](https://kb.adguard.com/en/vpn) sections, repo
/intra.md

2022-03-30 14:16 UTC, vbagirov requested changes

2022-03-30 15:01 UTC, vbagirov approved these changes

2022-03-30 15:05 UTC, merged