Multiple wording fixes to AdGuard VPN Knowledge base
AdguardTeam/KnowledgeBaseVPN pull request #58
Opened 2022-12-07 14:21 UTC by anastasiia-fedotova

2022-12-08 08:55 UTC, el-termikael requested changes

2022-12-08 08:55 UTC, el-termikael commented on docs/adguard-vpn-for-mac/installation.md
> +1. To install AdGuard VPN for Mac, just follow [this link](https://agrd.io/mac_vpn) or open a browser, type *adguard-vpn.com* in the address bar and on the opened page click "Download".
всё ок, разве что тут кавычки, хотя для других кнопок используем курсив

2022-12-09 11:35 UTC, vyanovsky approved these changes

2022-12-12 12:26 UTC, el-termikael approved these changes

2022-12-12 12:28 UTC, merged