An article about dns leaks
AdguardTeam/KnowledgeBaseVPN pull request #87
Opened 2023-02-08 11:53 UTC by anastasiia-fedotova

2023-02-08 12:17 UTC, el-termikael commented on docs/general/dns-leaks.md
> +title: 'What is a DNS leak'
What is a DNS leak?

2023-02-08 12:20 UTC, el-termikael commented on docs/general/dns-leaks.md
> +## What are DNS leaks
What are DNS leaks?

2023-02-08 12:22 UTC, el-termikael commented on docs/general/dns-leaks.md
> +DNS leaks when using a VPN is a situation where a connection to a DNS server goes outside your encrypted VPN tunnel and your data becomes visible to the ISP.
DNS leaks when using a VPN is a situation — звучит несогласованно

When you use a VPN, a connection to a DNS server may travel outside of the encrypted VPN tunnel and your traffic may become visible to the ISP.

2023-02-08 12:41 UTC, el-termikael commented on docs/general/dns-leaks.md
> +In other words, every time you open a website such as `google.com`, your browser sends a request to the ISP's DNS server and in return receives the IP address of the requested website. In this way, y
such as `google.com` можно и убрать

2023-02-08 12:43 UTC, el-termikael commented on docs/general/dns-leaks.md
> +There are all sorts of security scanner websites for detecting DNS leaks, such as `whoer.net`. It is worth understanding that these sites themselves are not perfect and their algorithms are not clear
security scanner websites —> anonymity check services

2023-02-08 12:44 UTC, el-termikael commented on docs/general/dns-leaks.md
> +There are all sorts of security scanner websites for detecting DNS leaks, such as `whoer.net`. It is worth understanding that these sites themselves are not perfect and their algorithms are not clear
It is worth understanding —> It should be understood

2023-02-08 12:48 UTC, el-termikael commented on docs/general/dns-leaks.md
> +Some security scanner websites consider the coincidence of the user's IP address and the DNS server's IP address to be a "good" result, indicating that there is no leakage. In reality, this is not th
security scanning website

2023-02-08 12:50 UTC, el-termikael commented on docs/general/dns-leaks.md
> +Some security scanner websites consider the coincidence of the user's IP address and the DNS server's IP address to be a "good" result, indicating that there is no leakage. In reality, this is not th
```suggestion
Some security scanning websites consider the coincidence of the user's IP address and the DNS server's IP address to be a "good" result, indicating that there are no leaks. In reality, such a match may indicate the use of a VPN. When VPN is disabled and the requests go to your ISP's DNS server, the IP address of the DNS server and your own one do not coincide.
```

2023-02-08 12:51 UTC, el-termikael commented on docs/general/dns-leaks.md
> +If you enable AdGuard VPN on your device and run a check on any of the scanner websites, it finds that DNS queries go to the [AdGuard DNS](https://adguard-dns.io/en/welcome.html) servers. However, th
https://adguard-dns.io/welcome.html

2023-02-08 12:53 UTC, el-termikael commented on docs/general/dns-leaks.md
> +Using a non-filtering AdGuard DNS server is set by default in AdGuard VPN. This ensures that your queries do not go to the DNS servers of your ISP, which means that you keep your privacy and anonymit
```suggestion
Using a non-filtering AdGuard DNS server is set by default in AdGuard VPN. This ensures that your queries do not go to the DNS servers of your ISP, which means that you stay private and anonymous online.
```

2023-02-08 12:53 UTC, el-termikael commented on docs/general/dns-leaks.md
> +What's more, AdGuard DNS is a very popular DNS service, used by over 50 million people. What does this mean for you? Imagine the following situation: the usual VPN service uses the DNS server which i
50 million??

2023-02-08 12:55 UTC, el-termikael commented on docs/general/dns-leaks.md
> +What's more, AdGuard DNS is a very popular DNS service, used by over 50 million people. What does this mean for you? Imagine the following situation: the usual VPN service uses the DNS server which i
The number of its users hardly exceeds 1,000. — это Костя сказал, да?

2023-02-08 12:56 UTC, el-termikael commented on docs/general/dns-leaks.md
> +And in the case of AdGuard DNS you will "merge" with 50 million users, and you can't be tracked just by the fact of using the DNS server.
```suggestion
And in the case of AdGuard DNS you will "merge" with 50 million users so nobody will be able to track you by the fact of using the DNS server.
```
но вообще звучит так, будто у нас один сервер на 50 (35) миллионов пользователей

2023-02-08 12:57 UTC, el-termikael commented on docs/general/dns-leaks.md
> +There are many popular public DNS servers from [well-known DNS providers](https://adguard-dns.io/kb/en/general/dns-providers/). Some of them can only perform their direct duties – giving the IP addre
https://adguard-dns.io/kb/general/dns-providers

2023-02-08 12:57 UTC, el-termikael commented on docs/general/dns-leaks.md
> +For example, the filtering AdGuard DNS removes ads and protects your device from being tracked, while AdGuard DNS Family Protection combines AdGuard DNS features with Safe search and Parental control
the filtering AdGuard DNS — этоо название серера или что?

2023-02-08 13:31 UTC, anastasiia-fedotova commented on docs/general/dns-leaks.md
> +What's more, AdGuard DNS is a very popular DNS service, used by over 50 million people. What does this mean for you? Imagine the following situation: the usual VPN service uses the DNS server which i
про 50 млн - инфа с сайта
про 1000 юзеров - инфа от Андрея

2023-02-08 13:34 UTC, anastasiia-fedotova commented on docs/general/dns-leaks.md
> +For example, the filtering AdGuard DNS removes ads and protects your device from being tracked, while AdGuard DNS Family Protection combines AdGuard DNS features with Safe search and Parental control
Не, название у него просто AdGuard DNS. Ноо, почему-то захотелось сделать акцент на то, что он фильтрующий.

2023-02-08 14:02 UTC, ameshkov requested changes

2023-02-08 14:02 UTC, ameshkov commented on docs/general/dns-leaks.md
> +If you enable AdGuard VPN on your device and run a check on any of the scanner websites, it finds that DNS queries go to the [AdGuard DNS](https://adguard-dns.io/welcome.html) servers. However, this
```suggestion
If you enable AdGuard VPN on your device and run a check on any of the scanner websites, it finds that DNS queries go to the [AdGuard DNS](https://adguard-dns.io/) servers. However, this cannot be considered a leak.
```

2023-02-08 14:02 UTC, ameshkov commented on docs/general/dns-leaks.md
> +And in the case of AdGuard DNS you will "merge" with 50 million users so nobody will be able to track you by the fact of using the DNS server.
```suggestion
And in the case of AdGuard DNS you will "merge" with 50 million users so nobody will be able to track you by the mere fact of using that DNS server.
```

2023-02-09 09:57 UTC, ameshkov approved these changes

2023-02-09 10:43 UTC, el-termikael commented on docs/general/dns-leaks.md
> +title: 'What a DNS leak is'
не, тут лучше было оставить с вопросом: посмотри на оглавление днс кб: What is DNS? / What is AdGuard DNS? / What is Private AdGuard DNS?

2023-02-09 14:55 UTC, el-termikael approved these changes

2023-02-10 09:20 UTC, merged